---
title: "Projekt2.0"
author: "Michał Baran"
date: "20 maja 2019"
output: html_document
---

```{r, message=FALSE, results='hide', echo=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(tseries)
```

```{r}
#długość
n <- c(10,50,100,200)
#prawdopodobieństwo
p <- c(0.1,0.3,0.5,0.9)
#par_1
par1 <- c(5,4)
#par_2
par2 <- c(10,5)
#ilość symulacji
N <- 100
#alpha
alpha <- 0.1
#testy
testy <- c("SW","JB")
```


```{r}
data1 <- expand.grid(n,p,testy)
colnames(data1) <- c("Dlugosc", "Prawdopodobienstwo","Test")

```


```{r}
set.seed(20)

powers <- sapply(1:nrow(data1),
                 function(i){
                   n <- data1[i, 1]
                   p <- data1[i, 2]
                   test <- data1[i, 3]
                   
                   p_vector <- sapply(rep(n, N), function(x){
                     sample <- rmix(n, "norm", par1, "norm", par2, p)
                     
                     if (test == "SW"){
                       result <- shapiro.test(sample)$p.value
                     } else if (test == "JB"){
                       result <- jarque.bera.test(sample)$p.value
                     }   
                     result
                   })
                   mean(p_vector < alpha)
                 })

data2 <- bind_cols(data1, Moc = powers)
```


```{r, warning= FALSE, echo=FALSE, message=FALSE}
ggplot(data2,aes(x = Dlugosc, y = Moc, color = Test)) +
  labs(x = "Długość próby", y = "Moc") +
  geom_smooth() + 
  facet_wrap(~ Prawdopodobienstwo, nrow = 3)
```

```{r}
#długość
n <- c(10,50,100,200)
#prawdopodobieństwo
p <- 0.6
#par_2
par2 <- c(6,2)
#dane do zmiany
zmiana <- seq(2,10, by = .25)


data3 <- expand.grid(Dlugosc = n, Prawdo = p, Zmiana = zmiana, Test = testy)
```


```{r}
set.seed(20)

powers <- sapply(1:nrow(data3),
                 function(i){
                   n <- data3[i, 1]
                   par1 <- data3[i, 3]  
                   test <- data3[i, 4]
                   
                   p_vector <- sapply(rep(n, N), function(x){
                     sample <- rmix(n, "norm", c(par1,1), "norm", par2, p)
                     
                     if (test == "SW"){
                       result <- shapiro.test(sample)$p.value
                     } else if (test == "JB"){
                       result <- jarque.bera.test(sample)$p.value
                     }   
                     result
                   })
                   mean(p_vector < alpha)
                 })

data4 <- bind_cols(data3, Moc = powers)

data4 %>%
  ggplot(aes(x = Zmiana, y = Moc, color = Test)) +
  labs(x = "Wartosc par1[1]", y = "Moc") +
  geom_smooth() + 
  facet_wrap(~ Dlugosc, nrow = 3)
```



```{r}
set.seed(20)

powers <- sapply(1:nrow(data3),
                 function(i){
                   n <- data3[i, 1]
                   par1 <- data3[i, 3]  
                   test <- data3[i, 4]
                   
                   p_vector <- sapply(rep(n, N), function(x){
                     sample <- rmix(n, "norm", c(1,par1), "norm", par2, p)
                     
                     if (test == "SW"){
                       result <- shapiro.test(sample)$p.value
                     } else if (test == "JB"){
                       result <- jarque.bera.test(sample)$p.value
                     }   
                     result
                   })
                   mean(p_vector < alpha)
                 })

data4 <- bind_cols(data3, Moc = powers)

data4 %>%
  ggplot(aes(x = Zmiana, y = Moc, color = Test)) +
  labs(x = "Wartosc par1[1]", y = "Moc") +
  geom_smooth() + 
  facet_wrap(~ Dlugosc, nrow = 3)
```
